### ISSUE TITLE
Add vim support

### ISSUE THREAD

**Issue by kwokhou** [jake-stewart/jfind#11]
Please add support to `vim`.

**Comment by jake-stewart** [comment]
https://github.com/jake-stewart/jfind.vim

please note that I will not be extending the feature set of jfind for regular vim since I do not use it. This plugin supports opening jfind fullscreen within vim, or as a tmux popup. It supports the same exclude/format paths/keybinding from the neovim plugin, but will be missing the new features I am working on at the moment.

Opening jfind fullscreen within vim has a slight flicker. I will take a closer look at this another time. The tmux window works great though.
